import { useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, Clock3, Download, RefreshCw, TriangleAlert } from 'lucide-react'
import { api } from './api'

type Range = '24h' | '7d' | '30d'
type Metrics = { checks: number; successful_checks: number; failed_checks: number; uptime: number | null; average_response_time: number | null; p95_response_time: number | null; incident_count: number; downtime_seconds: number }
type AnalyticsData = { range: Range; summary: Metrics; monitors: ({ id: number; name: string } & Metrics)[]; series: { monitor_id: number; checked_at: string; response_time: number; ok: boolean }[] }

const duration = (seconds: number) => seconds < 60 ? `${seconds}s` : seconds < 3600 ? `${Math.round(seconds / 60)}m` : `${(seconds / 3600).toFixed(1)}h`

export function Analytics() {
  const [range, setRange] = useState<Range>('24h')
  const [data, setData] = useState<AnalyticsData | null>(null)
  const [error, setError] = useState('')
  const load = useCallback(() => api<AnalyticsData>(`/analytics?range=${range}`).then((result) => { setData(result); setError('') }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load analytics')), [range])
  useEffect(() => { void load() }, [load])
  const points = useMemo(() => { if (!data?.series.length) return ''; const max = Math.max(...data.series.map((item) => item.response_time), 1); return data.series.map((item, index) => `${(index / Math.max(data.series.length - 1, 1)) * 700},${180 - (item.response_time / max) * 160}`).join(' ') }, [data])
  const exportCsv = () => { if (!data) return; const rows = [['Monitor', 'Uptime', 'Average response (ms)', 'P95 response (ms)', 'Checks', 'Failed', 'Incidents', 'Downtime (seconds)'], ...data.monitors.map((item) => [item.name, item.uptime?.toFixed(3) ?? '', item.average_response_time ?? '', item.p95_response_time ?? '', item.checks, item.failed_checks, item.incident_count, item.downtime_seconds])]; const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = `pingava-${range}.csv`; link.click(); URL.revokeObjectURL(link.href) }
  return <section className="analytics"><div className="analytics-toolbar"><div className="range-tabs" role="tablist">{(['24h', '7d', '30d'] as Range[]).map((item) => <button role="tab" aria-selected={range === item} className={range === item ? 'active' : ''} onClick={() => setRange(item)} key={item}>{item === '24h' ? '24 hours' : item === '7d' ? '7 days' : '30 days'}</button>)}</div><button className="secondary-btn" onClick={exportCsv} disabled={!data}><Download size={15} />Export CSV</button></div>{error && <div className="page-error"><TriangleAlert size={16} />{error}<button onClick={() => void load()}><RefreshCw size={14} /></button></div>}<section className="analytics-metrics"><article><span>Period uptime</span><strong>{data?.summary.uptime == null ? 'No data' : `${data.summary.uptime.toFixed(2)}%`}</strong></article><article><span>Average response</span><strong>{data?.summary.average_response_time == null ? 'No data' : `${data.summary.average_response_time} ms`}</strong></article><article><span>P95 response</span><strong>{data?.summary.p95_response_time == null ? 'No data' : `${data.summary.p95_response_time} ms`}</strong></article><article><span>Downtime</span><strong>{duration(data?.summary.downtime_seconds || 0)}</strong></article></section><section className="analytics-chart"><div className="section-title"><div><h2>Response time</h2><p>{data?.summary.checks || 0} checks in this period</p></div><Clock3 size={17} /></div><div className="analytics-plot">{points ? <svg viewBox="0 0 700 200" preserveAspectRatio="none" aria-label="Response time history"><line x1="0" y1="180" x2="700" y2="180" /><line x1="0" y1="100" x2="700" y2="100" /><line x1="0" y1="20" x2="700" y2="20" /><polyline points={points} /></svg> : <div className="chart-empty"><Activity size={20} />Response history will appear after checks run.</div>}</div></section><section className="monitors-section analytics-table"><div className="section-title"><div><h2>Monitor performance</h2><p>Comparison for the selected period</p></div></div><div className="analytics-row analytics-head"><span>Monitor</span><span>Uptime</span><span>Average</span><span>P95</span><span>Checks</span><span>Incidents</span><span>Downtime</span></div>{data?.monitors.map((monitor) => <div className="analytics-row" key={monitor.id}><strong>{monitor.name}</strong><span>{monitor.uptime == null ? '—' : `${monitor.uptime.toFixed(2)}%`}</span><span>{monitor.average_response_time == null ? '—' : `${monitor.average_response_time} ms`}</span><span>{monitor.p95_response_time == null ? '—' : `${monitor.p95_response_time} ms`}</span><span>{monitor.checks}<small>{monitor.failed_checks ? `${monitor.failed_checks} failed` : 'All passed'}</small></span><span>{monitor.incident_count}</span><span>{duration(monitor.downtime_seconds)}</span></div>)}</section></section>
}
