import type { ReactNode } from 'react'
import { PublicFooter, PublicHeader } from './MarketingPages'
import { PageMetadata } from './Seo'
import './LegalPages.css'

const CONTACT_EMAIL = 'connect@pingava.com'

function LegalLayout({ title, description, children }: { title: string; description: string; children: ReactNode }) {
  const canonicalPath = title === 'Terms of Service' ? '/terms' : '/privacy'
  return <div className="legal-page"><PageMetadata title={`${title} | Pingava`} description={description} canonicalPath={canonicalPath} /><PublicHeader /><main><header><p>LEGAL</p><h1>{title}</h1><span>Last updated: September 2026</span></header><article>{children}</article></main><PublicFooter /></div>
}

export function TermsPage() {
  return <LegalLayout title="Terms of Service" description="Terms governing access to and use of the Pingava website and monitoring service.">
    <section><h2>1. Acceptance of terms</h2><p>By creating an account, accessing, or using Pingava, you agree to these Terms of Service. If you do not agree, do not use the service. If you use Pingava on behalf of an organization, you represent that you are authorized to accept these terms for that organization.</p></section>
    <section><h2>2. About Pingava</h2><p>Pingava is a website and API monitoring service. It can run scheduled requests against endpoints you configure, record results and response times, create incidents, send notifications, and publish selected information on public status pages.</p></section>
    <section><h2>3. Accounts and responsibilities</h2><p>You must provide accurate account information, keep your credentials secure, and promptly notify us if you believe your account has been accessed without authorization. You are responsible for activity performed through your account and for ensuring that you have permission to monitor every endpoint you configure.</p></section>
    <section><h2>4. Acceptable use</h2><p>You may not use Pingava to violate law, probe or attack systems without authorization, distribute malicious content, interfere with the service, evade usage limits, abuse third-party infrastructure, or attempt to access another user&apos;s account or data. Monitoring must be limited to systems you own or are expressly authorized to test.</p></section>
    <section><h2>5. Monitoring limitations</h2><p>Monitoring results are observations from Pingava&apos;s available infrastructure and may not reflect every user&apos;s experience. Results can be affected by network conditions, endpoint behavior, configuration, rate limits, maintenance, or third-party services. Pingava is not a substitute for your own operational, security, backup, or disaster-recovery controls.</p></section>
    <section><h2>6. Availability and notifications</h2><p>The service is provided on an as-available basis. We do not promise uninterrupted availability or guarantee any uptime level. Checks, incident detection, emails, webhooks, and other alerts may occasionally be delayed, duplicated, or fail. You should not rely on Pingava as the only notification channel for critical systems.</p></section>
    <section><h2>7. Plans and payments</h2><p>Some features may be offered free of charge and others may require a paid subscription. When paid plans are available, prices, billing periods, included usage, renewal terms, and applicable taxes will be presented before purchase. Unless stated otherwise at purchase, fees already charged are non-refundable except where required by law.</p></section>
    <section><h2>8. Intellectual property</h2><p>Pingava and its software, design, branding, and service content are owned by Pingava or its licensors and are protected by applicable intellectual-property laws. These terms give you a limited, non-exclusive right to use the service; they do not transfer ownership. You retain ownership of information you submit to the service.</p></section>
    <section><h2>9. Limitation of liability</h2><p>To the maximum extent permitted by applicable law, Pingava and its operator will not be liable for indirect, incidental, special, consequential, or punitive damages, or for loss of profits, revenue, data, goodwill, or business opportunity arising from use of or inability to use the service. Any direct liability will be limited to the amount you paid for the service during the three months before the event giving rise to the claim.</p></section>
    <section><h2>10. Suspension and termination</h2><p>We may restrict or suspend access when reasonably necessary to protect Pingava, its users, or third parties; respond to suspected misuse; comply with law; or address unpaid fees. You may stop using Pingava at any time. Provisions that by their nature should survive termination, including ownership and liability provisions, will continue to apply.</p></section>
    <section><h2>11. Changes</h2><p>We may update the service or these terms as Pingava evolves. Material changes will be reflected by updating the date on this page and, where practical, by providing additional notice. Continued use after updated terms take effect means you accept the revised terms.</p></section>
    <section><h2>12. Governing law</h2><p>These terms are governed by the laws applicable in the jurisdiction where Pingava&apos;s operator is established, without regard to conflict-of-law rules. Courts with lawful jurisdiction over the operator will have jurisdiction, except where consumer-protection law requires otherwise.</p></section>
    <section><h2>13. Contact</h2><p>Questions about these terms can be sent to <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</p></section>
  </LegalLayout>
}

export function PrivacyPage() {
  return <LegalLayout title="Privacy Policy" description="How Pingava collects, uses, and retains information when operating its monitoring service.">
    <section><h2>1. Information you provide</h2><p>When you create or manage an account, we collect information such as your name, email address, authentication details, workspace settings, and communications you send to us.</p></section>
    <section><h2>2. Google Sign-In</h2><p>If you choose Google Sign-In, Pingava receives basic account information made available through that sign-in flow, such as your Google account identifier, name, and email address. Google&apos;s handling of your information is governed by its own policies.</p></section>
    <section><h2>3. Monitor and status-page configuration</h2><p>We store the website URLs, API endpoints, monitoring rules, alert preferences, and other request configuration you choose to provide so Pingava can perform checks and operate your workspace. Public status-page information you choose to publish is visible to visitors of that page.</p></section>
    <section><h2>4. Usage and technical information</h2><p>Pingava records service usage and operational information such as check results, response times, HTTP status codes, incident history, delivery outcomes, IP address, browser or device information, authentication events, application errors, and security or server logs. We also use analytics to understand how the website and product are used.</p></section>
    <section><h2>5. Cookies and sessions</h2><p>We use cookies or similar browser storage where needed to maintain authenticated sessions, protect requests, remember relevant preferences, and measure product usage. Disabling essential cookies may prevent sign-in or other account features from working.</p></section>
    <section><h2>6. How we use information</h2><p>We use information to provide and secure accounts, perform monitoring checks, display history and incidents, deliver requested alerts, operate status pages, troubleshoot errors, prevent misuse, improve the service, communicate about the account, and comply with legal obligations.</p></section>
    <section><h2>7. Service providers</h2><p>Pingava relies on service providers to operate the product, including hosting and infrastructure providers, database hosting, transactional email delivery, Google authentication, and product analytics services such as Google Analytics and PostHog. These providers process information on our behalf or under their own applicable terms to deliver their services.</p></section>
    <section><h2>8. Data security</h2><p>We use reasonable administrative and technical measures intended to protect information and limit access. No online service or transmission method is completely secure, so we cannot guarantee absolute security. You are responsible for protecting your credentials and choosing appropriate information to include in monitor configuration.</p></section>
    <section><h2>9. Data retention</h2><p>We retain account and configuration information while an account is active and retain operational records according to the retention controls used by the service. Some records may remain temporarily in backups, security logs, or where required for legal, fraud-prevention, or dispute-resolution purposes.</p></section>
    <section><h2>10. Account and data deletion</h2><p>You may request account or data deletion by contacting us. We may need to verify your identity before completing a request. Certain information may be retained where reasonably necessary to meet legal obligations, protect the service, resolve disputes, or maintain security records.</p></section>
    <section><h2>11. Your rights</h2><p>Depending on the law that applies to you, you may have rights to request access to, correction of, deletion of, or restriction of certain personal information, or to object to particular processing. Contact us to make a request. We may ask for information needed to verify your identity and determine the applicable requirements.</p></section>
    <section><h2>12. Changes to this policy</h2><p>We may update this policy as Pingava changes. We will update the date shown above and, where practical, provide additional notice of material changes.</p></section>
    <section><h2>13. Contact</h2><p>Privacy questions and account or data requests can be sent to <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</p></section>
  </LegalLayout>
}
